description: pre_taining

target:
  name: msroctobasicvc
  service: singularity
  workspace_name: ml_ts_ws_240915

environment:  
  image: amlt-sing/acpt-torch2.3.1-py3.10-cuda12.1-ubuntu22.04  # amlt-sing/ptca-1.13.1-cuda11.7  # amlt-sing/pytorch-1.11.0-cuda11.6

storage:
  data:
    storage_account_name: mltsstorage240915
    container_name: v-haoli
    mount_dir: /mnt/storage

code:
  local_dir: C:\Users\v-haoli4\amlt\Time-MoE

jobs:
  - name: time_moe_2_4B
    sku:  NDAMv4:80G8
    priority: medium
    preemptible: True
    identity: managed
    command: 
    - conda create -n time_moe python=3.10 -y
    - source activate time_moe
    - pip install -r requirements.txt
    - pip install flash-attn==2.6.3
    - python torch_dist_run.py main.py -d /mnt/storage/pretraining_data/time300b/ --global_batch_size 128 --micro_batch_size 16 --precision bf16 --config_path TimeMoE-Ultra.json --save_steps 50000 --save_strategy steps --save_total_limit 10 --from_scratch 
    submit_args: 
      env:
        {
          AMLT_BLOB_ROOT_DIR: "/mnt/storage/",
          AZURE_BLOB_ROOT: "/mnt/storage/",
          WANDB_API_KEY: "dbed33c088333b75f780fbcb8dd936819a253011",
          HUGGINGFACE_HUB_TOKEN: "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",
          _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/e033d461-1923-44a7-872b-78f1d35a86dd/resourcegroups/ml-ts/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ml_ts_uai_240915",
        }
